### ISSUE TITLE
Crashing with Create

### ISSUE THREAD

**Issue by MrEcko19** [VulpTheHorseDog/Tomes#1]
I can't tell you more than the title does.

I'm trying to put this mod in a modpack and it's crashing before it launches with Create mixins or something like that.

**Comment by VulpTheHorseDog** [comment]
Is this with Tomes 1.0 or 1.1? if 1.0, update the mod and try again just in case. If it still doesn't work, I'd like the full crash log.

**Comment by MrEcko19** [comment]
It's qith the lastest version you uploaded. Here you have the crash lo
[crash-2021-10-12_11.54.05-fml.txt](https://github.com/VulpTheHorseDog/Tomes/files/7328883/crash-2021-10-12_11.54.05-fml.txt)
g.
