### ISSUE TITLE
Airy Protection + Angel Spellstone

### ISSUE THREAD

**Issue by TBone311xXx** [VulpTheHorseDog/Tomes#10]
Enigmatic legacy's Angel spellstone equipped, while trying to use Airy Protection tome in offhand crashes servers when both actuate at the same time

**Comment by belathus** [comment]
This appears to be the crash report on the server side: https://gist.github.com/belathus/3352c0bc34bd72985c10e15482dbe5c9

There is a second crash 1 minute later due to the Server Watchdog.

**Comment by VulpTheHorseDog** [comment]
A fix has been attempted in version 1.5. Sorry for the wait.
