### ISSUE TITLE
Crash when added to Crucial 2

### ISSUE THREAD

**Issue by Viatos** [VulpTheHorseDog/Tomes#5]
Adding a handful of mods to a Crucial 2 installation, I eventually tracked an initialization crash to be the Tomes mod. Like other reported crashes, this happens before a crash log can be generated. Given the size of the modpack this probably isn't very helpful but I figured it might have some minor utility as an additional datapoint in conjunction with the other reports.

**Comment by VulpTheHorseDog** [comment]
Gonna go ahead and close this issue just to clear the tracker. Feel free to reopen if it proves to still be a problem.
