### ISSUE TITLE
[Bug] Self Propulsion also sends other players forward on server

### ISSUE THREAD

**Issue by RhanCandia** [VulpTheHorseDog/Tomes#8]
I am currently playing Valhelsia 3 and everytime I use Self Propulsion, all other players in the server is getting pushed forward even though they are thousands of blocks away from me.

The effect icon shows up on their screen as well when I use it.

**Comment by PhunStyle** [comment]
Can confirm this happens on our server as well.

**Comment by VulpTheHorseDog** [comment]
_Should_ be sorted as of the new version, 1.3.
